---
- name: Disable Windows user accounts on Hyper-V VM
  hosts: all
  gather_facts: no
  tasks:
- name: Disable user accounts
      win_user:
        name: "{{ item }}"
        account_disabled: yes
      loop: "{{ users_to_disable }}"
