---
- name: Disable Windows user accounts on Hyper-V VM
  hosts: all
  gather_facts: no
  tasks:
  - name: Disable user account
    ansible.windows.win_powershell:
      script: Get-LocalUser | Where-Object {$_.Name -ne "administrator"} | Disable-LocalUser
