---
- name: Disable Windows user accounts on Hyper-V VM
  hosts: 52346
  gather_facts: no
  tasks:
    - name: Disable user accounts
      win_user:
        name: "{{ item }}"
        state: disabled
      loop: "{{ users_to_disable }}"
