---
- name: Disable Windows user accounts on Hyper-V VM
  hosts: all
  gather_facts: no
  tasks:
    - name: Disable user accounts
      win_command: |
        $users = "{{ users_to_disable }}"
        foreach ($user in $users) {
          net user $user /active:no
        }
